services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - CHATGANTT_ENV=dev
    volumes:
      - ./backend/app:/app/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    restart: unless-stopped
